### ISSUE TITLE
Remove prestop configuration from deployment.yaml

### ISSUE THREAD

**Issue by scottfrederick** [spring-guides/top-spring-on-kubernetes#8]
The following should be removed from the example `deployment.yaml` file: 

```
          lifecycle:
            preStop:
              exec:
                command: ["sh", "-c", "sleep 10"]
```

The `preStop` is not necessary since Spring Boot apps handle `SIGTERM` notifications and gracefully shut down. 

In addition, Docker images for applications are often built with distroless base images that do not include a shell, so commands like the `sh -c sleep 10` recommended here will not work. The `./mvnw spring-boot:build-image` command suggested in this guide will use a base image that does not include a shell [starting with Spring Boot 3.4](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.4.0-M1-Release-Notes#paketo-tiny-builder-for-building-oci-images).
